/// Flutter icons GameIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GameIcons
///      fonts:
///       - asset: fonts/GameIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GameIcons {
  GameIcons._();

  static const _kFontFam = 'GameIcons';
  static const String? _kFontPkg = null;

  static const IconData ________1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
